services:
  frontend:
    build: .
    container_name: cycling-media-frontend
    ports:
      - "8567:80"
    restart: unless-stopped
    networks:
      - cycling-media-network
    volumes:
      # Optional: Mount logs for debugging
      - ./docker/nginx/logs:/var/log/nginx
      # Mount src directory for live development
      - ./src:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - BACKEND_URL=http://backend:3001
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: cycling-media-backend
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - cycling-media-network
    volumes:
      - ./tmp/strava-images:/tmp/strava-images
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:8567
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  cycling-media-network:
    driver: bridge

volumes:
  logs:
    driver: local 